# Generated by Django 4.1.1 on 2022-11-13 01:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('length', models.TimeField()),
                ('note', models.TextField(max_length=512)),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='history.history')),
            ],
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kilograms', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('pounds', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('repetitions', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('kilometers', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('miles', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('time', models.TimeField()),
                ('isFinished', models.BooleanField(default=False)),
                ('isFailed', models.BooleanField(default=False)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.exercise')),
            ],
        ),
        migrations.AddField(
            model_name='exercise',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.workout'),
        ),
    ]
