# Generated by Django 4.1.1 on 2023-01-08 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0004_workout_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
