# Generated by Django 4.1.1 on 2023-03-11 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0005_alter_exercise_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='instructions',
            field=models.TextField(blank=True, max_length=2048),
        ),
    ]
